/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: operations["getHealthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness probe */
        get: operations["getReadyz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Build identity of this binary */
        get: operations["getVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an account and open a session */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Authenticate with email and password */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Authenticate with a Google ID token */
        post: operations["loginWithGoogle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/password/forgot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request a password reset email */
        post: operations["forgotPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/password/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set a new password using a reset token */
        post: operations["resetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/verify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Browser landing that opens the app deep link for email verification */
        get: operations["openEmailVerification"];
        put?: never;
        /** Confirm email using a verification token */
        post: operations["confirmEmail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/verify-email/resend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resend the email verification link */
        post: operations["resendEmailVerification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rotate a refresh token */
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke a refresh token */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current user profile */
        get: operations["getMe"];
        put?: never;
        post?: never;
        /**
         * Close the account and erase personal data
         * @description Cancels active marketplace commitments, anonymises personal data, and tombstones the user. Remaining MVP points are forfeited. Ledger history is retained without identifying data.
         */
        delete: operations["deleteMe"];
        options?: never;
        head?: never;
        /** Update the caller's display name */
        patch: operations["updateMe"];
        trace?: never;
    };
    "/v1/me/push-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Register Expo push token for this device */
        put: operations["putPushToken"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change password and revoke all refresh tokens */
        post: operations["changePassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/vehicles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The caller's vehicles (metadata only; no photo bytes) */
        get: operations["listVehicles"];
        put?: never;
        /** Register a vehicle */
        post: operations["createVehicle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/vehicles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["VehicleID"];
            };
            cookie?: never;
        };
        /** One of the caller's vehicles */
        get: operations["getVehicle"];
        put?: never;
        post?: never;
        /** Delete a vehicle and its photo */
        delete: operations["deleteVehicle"];
        options?: never;
        head?: never;
        /** Replace mutable vehicle fields */
        patch: operations["updateVehicle"];
        trace?: never;
    };
    "/v1/vehicles/{id}/photo": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["VehicleID"];
            };
            cookie?: never;
        };
        /** Download the vehicle photo (owner only) */
        get: operations["getVehiclePhoto"];
        /** Upload a JPEG or PNG photo (max 300 KiB) */
        put: operations["putVehiclePhoto"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/spots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Spots visible in a viewport, as GeoJSON */
        get: operations["listSpots"];
        put?: never;
        /** Announce a parking spot */
        post: operations["createSpot"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/spots/mine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The caller's own offers */
        get: operations["listMySpots"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/spots/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["SpotID"];
            };
            cookie?: never;
        };
        /** One spot as a GeoJSON feature */
        get: operations["getSpot"];
        put?: never;
        post?: never;
        /** Withdraw an offer */
        delete: operations["deleteSpot"];
        options?: never;
        head?: never;
        /** Edit an available offer (owner only) */
        patch: operations["updateSpot"];
        trace?: never;
    };
    "/v1/spots/{id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["SpotID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publish an unpublished parked-car reminder (owner only) */
        post: operations["publishSpot"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/spots/{id}/vehicle/photo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Photo of the vehicle linked to a spot */
        get: operations["getSpotVehiclePhoto"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/spots/{id}/offers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List offers for a listing owned by the caller */
        get: operations["listSpotOffers"];
        put?: never;
        /** Propose a dated exchange for a listing */
        post: operations["createOffer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/offers/mine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The caller's own offers */
        get: operations["listMyOffers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/offers/{id}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept an offer and atomically create its reservation */
        post: operations["acceptOffer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/offers/{id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject a pending offer as listing owner */
        post: operations["rejectOffer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/offers/{id}/withdraw": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Withdraw a pending offer as its driver */
        post: operations["withdrawOffer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reservations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The caller's recent reservations (as driver or owner) */
        get: operations["listReservations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reservations/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The caller's active reservations */
        get: operations["listActiveReservations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reservations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One reservation */
        get: operations["getReservation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reservations/{id}/rating": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rate the other party after a completed exchange */
        post: operations["rateReservation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/{id}/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Public profile with ratings */
        get: operations["getUserProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** File a moderation report (problem, listing, or profile) */
        post: operations["createReport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reservations/{id}/peer-vehicle/photo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Photo of the counterpart's vehicle on a reservation */
        get: operations["getReservationPeerVehiclePhoto"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reservations/{id}/en-route": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark that the caller is on the way to the exchange */
        post: operations["markReservationEnRoute"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reservations/{id}/location": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record the caller's latest en-route location fix */
        post: operations["updateReservationLocation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reservations/{id}/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark ready at the exchange point; completes when both parties are ready */
        post: operations["markReservationReady"];
        /** Retract the caller's ready signal */
        delete: operations["clearReservationReady"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reservations/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel a reservation */
        post: operations["cancelReservation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ws/tickets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Short-lived ticket for the WebSocket handshake */
        post: operations["issueSocketTicket"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ws": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Viewport-subscribed event stream */
        get: operations["openWebSocket"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            /** @example ok */
            status: string;
        };
        ReadyResponse: {
            status: string;
            database: string;
        };
        VersionResponse: {
            version: string;
            revision: string;
            build_time: string;
            go_version: string;
        };
        RegisterRequest: {
            /** Format: email */
            email: string;
            password: string;
            display_name: string;
            /**
             * @description Optional E.164 phone; shown to the other party after accept when set
             * @example +34600111222
             */
            phone?: string;
        };
        GoogleLoginRequest: {
            id_token: string;
        };
        ForgotPasswordRequest: {
            /** Format: email */
            email: string;
        };
        ResetPasswordRequest: {
            token: string;
            password: string;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        RefreshRequest: {
            refresh_token: string;
        };
        SessionResponse: {
            access_token: string;
            refresh_token: string;
            /** @example Bearer */
            token_type: string;
            /** @description Seconds remaining on the access token */
            expires_in: number;
            user: components["schemas"]["UserResponse"];
            /**
             * Format: int64
             * @description Present when this session credited the weekly login bonus. Clients should show an in-app notice — push often cannot deliver on first login because the Expo token is registered afterwards.
             */
            login_grant_cents?: number;
        };
        UserResponse: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            display_name: string;
            /** @description E.164 phone number of this account; empty when unset */
            phone: string;
            /**
             * @description Preferred UI and push notification language
             * @enum {string}
             */
            locale: "es" | "en";
            /** @description Whether the account may announce or reserve */
            email_verified: boolean;
            /** Format: double */
            rating?: number | null;
            rating_count: number;
            /** Format: int64 */
            balance_cents: number;
        };
        ConfirmEmailRequest: {
            token: string;
        };
        UpdateMeRequest: {
            display_name?: string;
            /**
             * @description E.164 phone, or empty string to clear
             * @example +34600111222
             */
            phone?: string;
            /**
             * @description Preferred UI and push notification language
             * @enum {string}
             */
            locale?: "es" | "en";
        };
        ChangePasswordRequest: {
            current_password: string;
            new_password: string;
        };
        VehicleResponse: {
            /** Format: uuid */
            id: string;
            plate: string;
            make_model: string;
            /** @enum {string} */
            size_class: "small" | "medium" | "large";
            color: string;
            year: number;
            has_photo: boolean;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        CreateVehicleRequest: {
            plate: string;
            make_model: string;
            /** @enum {string} */
            size_class: "small" | "medium" | "large";
            color: string;
            year: number;
        };
        UpdateVehicleRequest: {
            plate: string;
            make_model: string;
            /** @enum {string} */
            size_class: "small" | "medium" | "large";
            color: string;
            year: number;
        };
        /** @description Claimer-visible car identity embedded on spot features */
        VehicleSummary: {
            /** Format: uuid */
            id: string;
            plate: string;
            make_model: string;
            color: string;
            year: number;
            /** @enum {string} */
            size_class: "small" | "medium" | "large";
            has_photo: boolean;
        };
        CreateSpotRequest: {
            /** Format: double */
            lon: number;
            /** Format: double */
            lat: number;
            size_class: string;
            price_cents: number;
            address_hint?: string;
            notes?: string;
            /**
             * Format: uuid
             * @description One of the caller's vehicles; required so claimers know which car to meet
             */
            vehicle_id: string;
            /** Format: date-time */
            preferred_departure_at?: string | null;
            /** @default true */
            auto_cancel_no_show: boolean;
            /**
             * @description «Me voy ya» — short-lived listing with ETA-only offers
             * @default false
             */
            leaving_now: boolean;
            /**
             * @description Parked-car reminder; not shown on the public map until published
             * @default false
             */
            unpublished?: boolean;
        };
        /** @description Convert an unpublished parked reminder into a public listing. */
        PublishSpotRequest: {
            size_class?: string;
            price_cents: number;
            address_hint?: string;
            notes?: string;
            /** Format: uuid */
            vehicle_id: string;
            /** Format: date-time */
            preferred_departure_at?: string | null;
            /** @default true */
            auto_cancel_no_show?: boolean;
            /** @default false */
            leaving_now?: boolean;
        };
        /**
         * @description Partial edit of an available listing. Location, listing lifetime, and
         *     spot size_class are not editable.
         */
        UpdateSpotRequest: {
            price_cents?: number;
            notes?: string;
            /** Format: uuid */
            vehicle_id?: string;
            /** Format: date-time */
            preferred_departure_at?: string | null;
            auto_cancel_no_show?: boolean;
        };
        SpotProperties: {
            /** Format: uuid */
            owner_id: string;
            owner_name: string;
            /** Format: double */
            owner_rating?: number | null;
            /** @description Owner E.164 phone; only present when exact_location is true */
            owner_phone?: string;
            size_class: string;
            status: string;
            price_cents: number;
            address_hint?: string;
            notes?: string;
            /** Format: date-time */
            preferred_departure_at?: string | null;
            /** Format: date-time */
            listed_until: string;
            auto_cancel_no_show: boolean;
            /** @description Owner is leaving now («Me voy ya») */
            leaving_now?: boolean;
            exact_location: boolean;
            is_mine: boolean;
            /** @description Omitted until exact_location is true */
            vehicle?: components["schemas"]["VehicleSummary"];
        };
        GeoJSONPoint: {
            /** @enum {string} */
            type: "Point";
            /** @description [longitude, latitude] */
            coordinates: number[];
        };
        SpotFeature: {
            /** @enum {string} */
            type: "Feature";
            id?: string;
            geometry: components["schemas"]["GeoJSONPoint"];
            properties: components["schemas"]["SpotProperties"];
        };
        SpotFeatureCollection: {
            /** @enum {string} */
            type: "FeatureCollection";
            features: components["schemas"]["SpotFeature"][];
        };
        CreateOfferRequest: {
            /** Format: uuid */
            vehicle_id: string;
            /** Format: date-time */
            exchange_at: string;
            amount_cents: number;
        };
        OfferResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            spot_id: string;
            /** Format: uuid */
            driver_id: string;
            /** Format: uuid */
            vehicle_id: string;
            /** Format: date-time */
            exchange_at: string;
            amount_cents: number;
            /** @enum {string} */
            status: "pending" | "accepted" | "rejected" | "withdrawn" | "expired";
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            expires_at: string;
            /** @description Present when listing offers for the spot owner */
            driver_name?: string;
            /**
             * Format: double
             * @description Average stars when the driver has ratings; omitted if none
             */
            driver_rating?: number | null;
            /** @description Number of ratings received by the driver */
            driver_rating_count?: number;
        };
        ReservationResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            spot_id: string;
            /** Format: uuid */
            driver_id: string;
            /** Format: uuid */
            owner_id: string;
            status: string;
            price_cents: number;
            /** Format: uuid */
            offer_id?: string;
            /** Format: uuid */
            driver_vehicle_id?: string;
            /** @description Car occupying the spot (owner) — visible to both parties */
            owner_vehicle?: components["schemas"]["VehicleSummary"];
            /** @description Driver's car from the accepted offer — visible to both parties */
            driver_vehicle?: components["schemas"]["VehicleSummary"];
            /** Format: date-time */
            exchange_at: string;
            /** Format: date-time */
            owner_en_route_at?: string | null;
            /** Format: date-time */
            driver_en_route_at?: string | null;
            /** @description Direct distance in metres from the peer's latest fix to the meeting point. */
            peer_distance_m?: number | null;
            /**
             * Format: date-time
             * @description Timestamp of the peer fix used for peer_distance_m.
             */
            peer_location_measured_at?: string | null;
            /** Format: date-time */
            owner_ready_at?: string | null;
            /** Format: date-time */
            driver_ready_at?: string | null;
            /** @description Why the reservation ended when status is cancelled/expired. Values include owner, driver, driver_late, driver_no_show, owner_no_show, safety_net, safety_net_owner_ready. */
            cancel_reason?: string | null;
            /** Format: date-time */
            created_at: string;
            /** @description Spot meeting point for list/detail UX (navigate + re-announce). Exact coords; both reservation parties already shared this place. */
            spot_summary?: components["schemas"]["ReservationSpotSummary"];
            /** @description True when the caller may still submit a rating */
            can_rate?: boolean;
            my_rating?: components["schemas"]["RatingSummary"];
            peer_rating?: components["schemas"]["RatingSummary"];
        };
        ReservationLocationRequest: {
            /** Format: double */
            latitude: number;
            /** Format: double */
            longitude: number;
        };
        RateReservationRequest: {
            stars: number;
            comment?: string;
        };
        RatingSummary: {
            stars: number;
            comment?: string;
            rater_name?: string;
            /** Format: date-time */
            created_at: string;
        };
        PublicUserProfile: {
            /** Format: uuid */
            id: string;
            display_name: string;
            /** Format: double */
            rating?: number | null;
            rating_count: number;
            reviews: components["schemas"]["PublicReview"][];
        };
        PublicReview: {
            rater_name: string;
            stars: number;
            comment?: string;
            /** Format: date-time */
            created_at: string;
        };
        CreateReportRequest: {
            /** @description Free-text complaint */
            body: string;
            /**
             * Format: uuid
             * @description Set to report a listing (mutually exclusive with reported_user_id)
             */
            spot_id?: string;
            /**
             * Format: uuid
             * @description Set to report a public profile (mutually exclusive with spot_id)
             */
            reported_user_id?: string;
        };
        ReservationSpotSummary: {
            /** Format: double */
            lon: number;
            /** Format: double */
            lat: number;
            address_hint?: string;
            /** @description Guide price from the original spot listing */
            price_cents: number;
            /**
             * Format: uuid
             * @description Owner vehicle that was listed on the spot
             */
            vehicle_id?: string;
        };
        TicketResponse: {
            ticket: string;
            expires_in: number;
        };
        /** @description Client to server WebSocket message */
        ViewportMessage: {
            /** @enum {string} */
            type: "viewport";
            /** @description [west, south, east, north] */
            bbox: number[];
            zoom?: number;
            /** Format: date-time */
            from?: string;
            /** Format: date-time */
            to?: string;
            /** @description When true, include flexible (non-leaving-now) spots. Defaults to true when omitted. */
            include_flexible?: boolean;
            /** @description When true, include «Me voy ya» listings. Defaults to true when omitted. */
            include_leaving_now?: boolean;
            /** @description When true, return only leaving_now listings. */
            leaving_now_only?: boolean;
        };
        /** @description Server to client WebSocket snapshot after a viewport */
        SnapshotMessage: {
            /** @enum {string} */
            type: "snapshot";
            features: components["schemas"]["SpotFeature"][];
        };
        /** @description Server to client incremental event */
        SpotEventMessage: {
            /** @enum {string} */
            type: "spot.added" | "spot.updated" | "spot.removed" | "reservation.updated" | "offer.created";
            /** Format: uuid */
            id: string;
            /** Format: double */
            lon: number;
            /** Format: double */
            lat: number;
            status?: string;
            price_cents?: number;
            exact_location: boolean;
            /** @description Owner is leaving now («Me voy ya») */
            leaving_now?: boolean;
        };
        ErrorEnvelope: {
            error: components["schemas"]["ErrorBody"];
        };
        ErrorBody: {
            code: string;
            message: string;
            fields?: {
                [key: string]: string;
            };
            request_id?: string;
        };
    };
    responses: {
        /** @description Uniform error envelope */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: {
        SpotID: string;
        VehicleID: string;
        ReservationID: string;
        OfferID: string;
        /** @description minLon,minLat,maxLon,maxLat */
        BBox: string;
        Zoom: number;
        /** @description Inclusive start of the time window (RFC3339) */
        From: string;
        /** @description Exclusive end of the time window (RFC3339) */
        To: string;
        /** @description When true, include flexible (non-preferred, non-leaving-now) spots */
        IncludeFlexible: boolean;
        /** @description When true, include «Me voy ya» listings */
        IncludeLeavingNow: boolean;
        /** @description When true, return only leaving_now listings */
        LeavingNowOnly: boolean;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Process can serve HTTP */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    getReadyz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Database is reachable */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyResponse"];
                };
            };
            /** @description Database is unreachable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyResponse"];
                };
            };
        };
    };
    getVersion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Version metadata */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionResponse"];
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Session issued */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            400: components["responses"]["Error"];
            409: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Session issued */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    loginWithGoogle: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoogleLoginRequest"];
            };
        };
        responses: {
            /** @description Session issued */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            401: components["responses"]["Error"];
            409: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    forgotPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotPasswordRequest"];
            };
        };
        responses: {
            /** @description Always returned when the request is well-formed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["Error"];
        };
    };
    resetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordRequest"];
            };
        };
        responses: {
            /** @description Password updated */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            422: components["responses"]["Error"];
        };
    };
    openEmailVerification: {
        parameters: {
            query: {
                token: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description HTML landing page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            422: components["responses"]["Error"];
        };
    };
    confirmEmail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmEmailRequest"];
            };
        };
        responses: {
            /** @description Email confirmed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            422: components["responses"]["Error"];
        };
    };
    resendEmailVerification: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sent when allowed (or already verified) */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description New session */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Token revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    deleteMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Account closed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
        };
    };
    updateMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMeRequest"];
            };
        };
        responses: {
            /** @description Updated profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            401: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    putPushToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description ExponentPushToken[...] */
                    token: string;
                    /** @enum {string} */
                    platform: "ios" | "android";
                };
            };
        };
        responses: {
            /** @description Token stored */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Password changed; existing refresh tokens revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    listVehicles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Vehicles */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VehicleResponse"][];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    createVehicle: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateVehicleRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VehicleResponse"];
                };
            };
            401: components["responses"]["Error"];
            409: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    getVehicle: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["VehicleID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Vehicle */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VehicleResponse"];
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    deleteVehicle: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["VehicleID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    updateVehicle: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["VehicleID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateVehicleRequest"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VehicleResponse"];
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    getVehiclePhoto: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["VehicleID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Image bytes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/jpeg": string;
                    "image/png": string;
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    putVehiclePhoto: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["VehicleID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "image/jpeg": string;
                "image/png": string;
            };
        };
        responses: {
            /** @description Photo stored */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    listSpots: {
        parameters: {
            query: {
                /** @description minLon,minLat,maxLon,maxLat */
                bbox: components["parameters"]["BBox"];
                zoom?: components["parameters"]["Zoom"];
                /** @description Inclusive start of the time window (RFC3339) */
                from?: components["parameters"]["From"];
                /** @description Exclusive end of the time window (RFC3339) */
                to?: components["parameters"]["To"];
                /** @description When true, include flexible (non-preferred, non-leaving-now) spots */
                include_flexible?: components["parameters"]["IncludeFlexible"];
                /** @description When true, include «Me voy ya» listings */
                include_leaving_now?: components["parameters"]["IncludeLeavingNow"];
                /** @description When true, return only leaving_now listings */
                leaving_now_only?: components["parameters"]["LeavingNowOnly"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description FeatureCollection of spots */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpotFeatureCollection"];
                };
            };
            400: components["responses"]["Error"];
        };
    };
    createSpot: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSpotRequest"];
            };
        };
        responses: {
            /** @description Created offer as a GeoJSON feature */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpotFeature"];
                };
            };
            401: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    listMySpots: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description FeatureCollection */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpotFeatureCollection"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    getSpot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["SpotID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Feature */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpotFeature"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    deleteSpot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["SpotID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Withdrawn */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    updateSpot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["SpotID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSpotRequest"];
            };
        };
        responses: {
            /** @description Updated offer as a GeoJSON feature */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpotFeature"];
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    publishSpot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["SpotID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PublishSpotRequest"];
            };
        };
        responses: {
            /** @description Published offer as a GeoJSON feature */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpotFeature"];
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    getSpotVehiclePhoto: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["SpotID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Image bytes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/jpeg": string;
                    "image/png": string;
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    listSpotOffers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["SpotID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Offers ordered by preferred-time match, then amount */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OfferResponse"][];
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    createOffer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["SpotID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOfferRequest"];
            };
        };
        responses: {
            /** @description Offer created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OfferResponse"];
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    listMyOffers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Offers submitted by the caller */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OfferResponse"][];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    acceptOffer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["OfferID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reservation created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReservationResponse"];
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    rejectOffer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["OfferID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rejected */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    withdrawOffer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["OfferID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Withdrawn */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    listReservations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reservations */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReservationResponse"][];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    listActiveReservations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active reservations */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReservationResponse"][];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    getReservation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ReservationID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reservation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReservationResponse"];
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    rateReservation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ReservationID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RateReservationRequest"];
            };
        };
        responses: {
            /** @description Rating created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RatingSummary"];
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    getUserProfile: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Public profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicUserProfile"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    createReport: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateReportRequest"];
            };
        };
        responses: {
            /** @description Report recorded */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    getReservationPeerVehiclePhoto: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ReservationID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Image bytes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/jpeg": string;
                    "image/png": string;
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    markReservationEnRoute: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ReservationID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description En-route recorded */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    updateReservationLocation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ReservationID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReservationLocationRequest"];
            };
        };
        responses: {
            /** @description Reservation view with the peer distance when available */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReservationResponse"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    markReservationReady: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ReservationID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ready recorded */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        completed: boolean;
                    };
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    clearReservationReady: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ReservationID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ready cleared */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    cancelReservation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ReservationID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cancelled */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    issueSocketTicket: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ticket issued */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketResponse"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    openWebSocket: {
        parameters: {
            query: {
                /** @description Ticket from POST /v1/ws/tickets; not an access token */
                ticket: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Protocol switched to WebSocket */
            101: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
        };
    };
}
