// Package contract provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package contract

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for GeoJSONPointType.
const (
	Point GeoJSONPointType = "Point"
)

// Valid indicates whether the value is a known member of the GeoJSONPointType enum.
func (e GeoJSONPointType) Valid() bool {
	switch e {
	case Point:
		return true
	default:
		return false
	}
}

// Defines values for SnapshotMessageType.
const (
	Snapshot SnapshotMessageType = "snapshot"
)

// Valid indicates whether the value is a known member of the SnapshotMessageType enum.
func (e SnapshotMessageType) Valid() bool {
	switch e {
	case Snapshot:
		return true
	default:
		return false
	}
}

// Defines values for SpotEventMessageType.
const (
	ReservationUpdated SpotEventMessageType = "reservation.updated"
	SpotAdded          SpotEventMessageType = "spot.added"
	SpotRemoved        SpotEventMessageType = "spot.removed"
	SpotUpdated        SpotEventMessageType = "spot.updated"
)

// Valid indicates whether the value is a known member of the SpotEventMessageType enum.
func (e SpotEventMessageType) Valid() bool {
	switch e {
	case ReservationUpdated:
		return true
	case SpotAdded:
		return true
	case SpotRemoved:
		return true
	case SpotUpdated:
		return true
	default:
		return false
	}
}

// Defines values for SpotFeatureType.
const (
	Feature SpotFeatureType = "Feature"
)

// Valid indicates whether the value is a known member of the SpotFeatureType enum.
func (e SpotFeatureType) Valid() bool {
	switch e {
	case Feature:
		return true
	default:
		return false
	}
}

// Defines values for SpotFeatureCollectionType.
const (
	FeatureCollection SpotFeatureCollectionType = "FeatureCollection"
)

// Valid indicates whether the value is a known member of the SpotFeatureCollectionType enum.
func (e SpotFeatureCollectionType) Valid() bool {
	switch e {
	case FeatureCollection:
		return true
	default:
		return false
	}
}

// Defines values for ViewportMessageType.
const (
	Viewport ViewportMessageType = "viewport"
)

// Valid indicates whether the value is a known member of the ViewportMessageType enum.
func (e ViewportMessageType) Valid() bool {
	switch e {
	case Viewport:
		return true
	default:
		return false
	}
}

// CreateSpotRequest defines model for CreateSpotRequest.
type CreateSpotRequest struct {
	AddressHint *string `json:"address_hint,omitempty"`

	// AvailableInMinutes Delay until the offer starts. Zero means immediately. Capped at 24 hours.
	AvailableInMinutes *int    `json:"available_in_minutes,omitempty"`
	DurationMinutes    int     `json:"duration_minutes"`
	Lat                float64 `json:"lat"`
	Lon                float64 `json:"lon"`
	Notes              *string `json:"notes,omitempty"`
	PriceCents         int     `json:"price_cents"`
	SizeClass          string  `json:"size_class"`
}

// ErrorBody defines model for ErrorBody.
type ErrorBody struct {
	Code      string             `json:"code"`
	Fields    *map[string]string `json:"fields,omitempty"`
	Message   string             `json:"message"`
	RequestId *string            `json:"request_id,omitempty"`
}

// ErrorEnvelope defines model for ErrorEnvelope.
type ErrorEnvelope struct {
	Error ErrorBody `json:"error"`
}

// GeoJSONPoint defines model for GeoJSONPoint.
type GeoJSONPoint struct {
	// Coordinates [longitude, latitude]
	Coordinates []float64        `json:"coordinates"`
	Type        GeoJSONPointType `json:"type"`
}

// GeoJSONPointType defines model for GeoJSONPoint.Type.
type GeoJSONPointType string

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status string `json:"status"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// ReadyResponse defines model for ReadyResponse.
type ReadyResponse struct {
	Database string `json:"database"`
	Status   string `json:"status"`
}

// RefreshRequest defines model for RefreshRequest.
type RefreshRequest struct {
	RefreshToken string `json:"refresh_token"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	DisplayName string              `json:"display_name"`
	Email       openapi_types.Email `json:"email"`
	Password    string              `json:"password"`
}

// ReservationResponse defines model for ReservationResponse.
type ReservationResponse struct {
	CreatedAt     time.Time          `json:"created_at"`
	DriverId      openapi_types.UUID `json:"driver_id"`
	EndsAt        time.Time          `json:"ends_at"`
	ExpiresAt     time.Time          `json:"expires_at"`
	Id            openapi_types.UUID `json:"id"`
	OwnerId       openapi_types.UUID `json:"owner_id"`
	PriceCents    int                `json:"price_cents"`
	ReconfirmBy   time.Time          `json:"reconfirm_by"`
	ReconfirmedAt *time.Time         `json:"reconfirmed_at,omitempty"`
	SpotId        openapi_types.UUID `json:"spot_id"`
	StartsAt      time.Time          `json:"starts_at"`
	Status        string             `json:"status"`
}

// SessionResponse defines model for SessionResponse.
type SessionResponse struct {
	AccessToken string `json:"access_token"`

	// ExpiresIn Seconds remaining on the access token
	ExpiresIn    int          `json:"expires_in"`
	RefreshToken string       `json:"refresh_token"`
	TokenType    string       `json:"token_type"`
	User         UserResponse `json:"user"`
}

// SnapshotMessage Server to client WebSocket snapshot after a viewport
type SnapshotMessage struct {
	Features []SpotFeature       `json:"features"`
	Type     SnapshotMessageType `json:"type"`
}

// SnapshotMessageType defines model for SnapshotMessage.Type.
type SnapshotMessageType string

// SpotEventMessage Server to client incremental event
type SpotEventMessage struct {
	ExactLocation bool                 `json:"exact_location"`
	Id            openapi_types.UUID   `json:"id"`
	Lat           float64              `json:"lat"`
	Lon           float64              `json:"lon"`
	PriceCents    *int                 `json:"price_cents,omitempty"`
	Status        *string              `json:"status,omitempty"`
	Type          SpotEventMessageType `json:"type"`
}

// SpotEventMessageType defines model for SpotEventMessage.Type.
type SpotEventMessageType string

// SpotFeature defines model for SpotFeature.
type SpotFeature struct {
	Geometry   GeoJSONPoint    `json:"geometry"`
	Id         *string         `json:"id,omitempty"`
	Properties SpotProperties  `json:"properties"`
	Type       SpotFeatureType `json:"type"`
}

// SpotFeatureType defines model for SpotFeature.Type.
type SpotFeatureType string

// SpotFeatureCollection defines model for SpotFeatureCollection.
type SpotFeatureCollection struct {
	Features []SpotFeature             `json:"features"`
	Type     SpotFeatureCollectionType `json:"type"`
}

// SpotFeatureCollectionType defines model for SpotFeatureCollection.Type.
type SpotFeatureCollectionType string

// SpotProperties defines model for SpotProperties.
type SpotProperties struct {
	AddressHint   *string            `json:"address_hint,omitempty"`
	AvailableFrom time.Time          `json:"available_from"`
	ExactLocation bool               `json:"exact_location"`
	ExpiresAt     time.Time          `json:"expires_at"`
	IsMine        bool               `json:"is_mine"`
	Notes         *string            `json:"notes,omitempty"`
	OwnerId       openapi_types.UUID `json:"owner_id"`
	OwnerName     string             `json:"owner_name"`
	OwnerRating   *float64           `json:"owner_rating,omitempty"`
	PriceCents    int                `json:"price_cents"`
	SizeClass     string             `json:"size_class"`
	Status        string             `json:"status"`
}

// TicketResponse defines model for TicketResponse.
type TicketResponse struct {
	ExpiresIn int    `json:"expires_in"`
	Ticket    string `json:"ticket"`
}

// UserResponse defines model for UserResponse.
type UserResponse struct {
	BalanceCents int64               `json:"balance_cents"`
	DisplayName  string              `json:"display_name"`
	Email        openapi_types.Email `json:"email"`
	Id           openapi_types.UUID  `json:"id"`
	Rating       *float64            `json:"rating,omitempty"`
	RatingCount  int                 `json:"rating_count"`
}

// VersionResponse defines model for VersionResponse.
type VersionResponse struct {
	BuildTime string `json:"build_time"`
	GoVersion string `json:"go_version"`
	Revision  string `json:"revision"`
	Version   string `json:"version"`
}

// ViewportMessage Client to server WebSocket message
type ViewportMessage struct {
	// Bbox [west, south, east, north]
	Bbox []float64           `json:"bbox"`
	From *time.Time          `json:"from,omitempty"`
	To   *time.Time          `json:"to,omitempty"`
	Type ViewportMessageType `json:"type"`
	Zoom *int                `json:"zoom,omitempty"`
}

// ViewportMessageType defines model for ViewportMessage.Type.
type ViewportMessageType string

// BBox defines model for BBox.
type BBox = string

// From defines model for From.
type From = time.Time

// ReservationID defines model for ReservationID.
type ReservationID = openapi_types.UUID

// SpotID defines model for SpotID.
type SpotID = openapi_types.UUID

// To defines model for To.
type To = time.Time

// Zoom defines model for Zoom.
type Zoom = int

// Error defines model for Error.
type Error = ErrorEnvelope

// ListSpotsParams defines parameters for ListSpots.
type ListSpotsParams struct {
	// Bbox minLon,minLat,maxLon,maxLat
	Bbox BBox  `form:"bbox" json:"bbox"`
	Zoom *Zoom `form:"zoom,omitempty" json:"zoom,omitempty"`

	// From Inclusive start of the time window (RFC3339)
	From *From `form:"from,omitempty" json:"from,omitempty"`

	// To Exclusive end of the time window (RFC3339)
	To *To `form:"to,omitempty" json:"to,omitempty"`
}

// OpenWebSocketParams defines parameters for OpenWebSocket.
type OpenWebSocketParams struct {
	// Ticket Ticket from POST /v1/ws/tickets; not an access token
	Ticket string `form:"ticket" json:"ticket"`
}

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// LogoutJSONRequestBody defines body for Logout for application/json ContentType.
type LogoutJSONRequestBody = RefreshRequest

// RefreshJSONRequestBody defines body for Refresh for application/json ContentType.
type RefreshJSONRequestBody = RefreshRequest

// RegisterJSONRequestBody defines body for Register for application/json ContentType.
type RegisterJSONRequestBody = RegisterRequest

// CreateSpotJSONRequestBody defines body for CreateSpot for application/json ContentType.
type CreateSpotJSONRequestBody = CreateSpotRequest
