// Package contract provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package contract

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for CreateVehicleRequestSizeClass.
const (
	CreateVehicleRequestSizeClassLarge  CreateVehicleRequestSizeClass = "large"
	CreateVehicleRequestSizeClassMedium CreateVehicleRequestSizeClass = "medium"
	CreateVehicleRequestSizeClassSmall  CreateVehicleRequestSizeClass = "small"
)

// Valid indicates whether the value is a known member of the CreateVehicleRequestSizeClass enum.
func (e CreateVehicleRequestSizeClass) Valid() bool {
	switch e {
	case CreateVehicleRequestSizeClassLarge:
		return true
	case CreateVehicleRequestSizeClassMedium:
		return true
	case CreateVehicleRequestSizeClassSmall:
		return true
	default:
		return false
	}
}

// Defines values for GeoJSONPointType.
const (
	Point GeoJSONPointType = "Point"
)

// Valid indicates whether the value is a known member of the GeoJSONPointType enum.
func (e GeoJSONPointType) Valid() bool {
	switch e {
	case Point:
		return true
	default:
		return false
	}
}

// Defines values for OfferResponseStatus.
const (
	Accepted  OfferResponseStatus = "accepted"
	Expired   OfferResponseStatus = "expired"
	Pending   OfferResponseStatus = "pending"
	Rejected  OfferResponseStatus = "rejected"
	Withdrawn OfferResponseStatus = "withdrawn"
)

// Valid indicates whether the value is a known member of the OfferResponseStatus enum.
func (e OfferResponseStatus) Valid() bool {
	switch e {
	case Accepted:
		return true
	case Expired:
		return true
	case Pending:
		return true
	case Rejected:
		return true
	case Withdrawn:
		return true
	default:
		return false
	}
}

// Defines values for SnapshotMessageType.
const (
	Snapshot SnapshotMessageType = "snapshot"
)

// Valid indicates whether the value is a known member of the SnapshotMessageType enum.
func (e SnapshotMessageType) Valid() bool {
	switch e {
	case Snapshot:
		return true
	default:
		return false
	}
}

// Defines values for SpotEventMessageType.
const (
	OfferCreated       SpotEventMessageType = "offer.created"
	ReservationUpdated SpotEventMessageType = "reservation.updated"
	SpotAdded          SpotEventMessageType = "spot.added"
	SpotRemoved        SpotEventMessageType = "spot.removed"
	SpotUpdated        SpotEventMessageType = "spot.updated"
)

// Valid indicates whether the value is a known member of the SpotEventMessageType enum.
func (e SpotEventMessageType) Valid() bool {
	switch e {
	case OfferCreated:
		return true
	case ReservationUpdated:
		return true
	case SpotAdded:
		return true
	case SpotRemoved:
		return true
	case SpotUpdated:
		return true
	default:
		return false
	}
}

// Defines values for SpotFeatureType.
const (
	Feature SpotFeatureType = "Feature"
)

// Valid indicates whether the value is a known member of the SpotFeatureType enum.
func (e SpotFeatureType) Valid() bool {
	switch e {
	case Feature:
		return true
	default:
		return false
	}
}

// Defines values for SpotFeatureCollectionType.
const (
	FeatureCollection SpotFeatureCollectionType = "FeatureCollection"
)

// Valid indicates whether the value is a known member of the SpotFeatureCollectionType enum.
func (e SpotFeatureCollectionType) Valid() bool {
	switch e {
	case FeatureCollection:
		return true
	default:
		return false
	}
}

// Defines values for UpdateMeRequestLocale.
const (
	UpdateMeRequestLocaleEn UpdateMeRequestLocale = "en"
	UpdateMeRequestLocaleEs UpdateMeRequestLocale = "es"
)

// Valid indicates whether the value is a known member of the UpdateMeRequestLocale enum.
func (e UpdateMeRequestLocale) Valid() bool {
	switch e {
	case UpdateMeRequestLocaleEn:
		return true
	case UpdateMeRequestLocaleEs:
		return true
	default:
		return false
	}
}

// Defines values for UpdateVehicleRequestSizeClass.
const (
	UpdateVehicleRequestSizeClassLarge  UpdateVehicleRequestSizeClass = "large"
	UpdateVehicleRequestSizeClassMedium UpdateVehicleRequestSizeClass = "medium"
	UpdateVehicleRequestSizeClassSmall  UpdateVehicleRequestSizeClass = "small"
)

// Valid indicates whether the value is a known member of the UpdateVehicleRequestSizeClass enum.
func (e UpdateVehicleRequestSizeClass) Valid() bool {
	switch e {
	case UpdateVehicleRequestSizeClassLarge:
		return true
	case UpdateVehicleRequestSizeClassMedium:
		return true
	case UpdateVehicleRequestSizeClassSmall:
		return true
	default:
		return false
	}
}

// Defines values for UserResponseLocale.
const (
	UserResponseLocaleEn UserResponseLocale = "en"
	UserResponseLocaleEs UserResponseLocale = "es"
)

// Valid indicates whether the value is a known member of the UserResponseLocale enum.
func (e UserResponseLocale) Valid() bool {
	switch e {
	case UserResponseLocaleEn:
		return true
	case UserResponseLocaleEs:
		return true
	default:
		return false
	}
}

// Defines values for VehicleResponseSizeClass.
const (
	VehicleResponseSizeClassLarge  VehicleResponseSizeClass = "large"
	VehicleResponseSizeClassMedium VehicleResponseSizeClass = "medium"
	VehicleResponseSizeClassSmall  VehicleResponseSizeClass = "small"
)

// Valid indicates whether the value is a known member of the VehicleResponseSizeClass enum.
func (e VehicleResponseSizeClass) Valid() bool {
	switch e {
	case VehicleResponseSizeClassLarge:
		return true
	case VehicleResponseSizeClassMedium:
		return true
	case VehicleResponseSizeClassSmall:
		return true
	default:
		return false
	}
}

// Defines values for VehicleSummarySizeClass.
const (
	VehicleSummarySizeClassLarge  VehicleSummarySizeClass = "large"
	VehicleSummarySizeClassMedium VehicleSummarySizeClass = "medium"
	VehicleSummarySizeClassSmall  VehicleSummarySizeClass = "small"
)

// Valid indicates whether the value is a known member of the VehicleSummarySizeClass enum.
func (e VehicleSummarySizeClass) Valid() bool {
	switch e {
	case VehicleSummarySizeClassLarge:
		return true
	case VehicleSummarySizeClassMedium:
		return true
	case VehicleSummarySizeClassSmall:
		return true
	default:
		return false
	}
}

// Defines values for ViewportMessageType.
const (
	Viewport ViewportMessageType = "viewport"
)

// Valid indicates whether the value is a known member of the ViewportMessageType enum.
func (e ViewportMessageType) Valid() bool {
	switch e {
	case Viewport:
		return true
	default:
		return false
	}
}

// Defines values for PutPushTokenJSONBodyPlatform.
const (
	Android PutPushTokenJSONBodyPlatform = "android"
	Ios     PutPushTokenJSONBodyPlatform = "ios"
)

// Valid indicates whether the value is a known member of the PutPushTokenJSONBodyPlatform enum.
func (e PutPushTokenJSONBodyPlatform) Valid() bool {
	switch e {
	case Android:
		return true
	case Ios:
		return true
	default:
		return false
	}
}

// ChangePasswordRequest defines model for ChangePasswordRequest.
type ChangePasswordRequest struct {
	CurrentPassword string `json:"current_password"`
	NewPassword     string `json:"new_password"`
}

// ConfirmEmailRequest defines model for ConfirmEmailRequest.
type ConfirmEmailRequest struct {
	Token string `json:"token"`
}

// CreateOfferRequest defines model for CreateOfferRequest.
type CreateOfferRequest struct {
	AmountCents int                `json:"amount_cents"`
	ExchangeAt  time.Time          `json:"exchange_at"`
	VehicleId   openapi_types.UUID `json:"vehicle_id"`
}

// CreateReportRequest defines model for CreateReportRequest.
type CreateReportRequest struct {
	// Body Free-text complaint
	Body string `json:"body"`

	// ReportedUserId Set to report a public profile (mutually exclusive with spot_id)
	ReportedUserId *openapi_types.UUID `json:"reported_user_id,omitempty"`

	// SpotId Set to report a listing (mutually exclusive with reported_user_id)
	SpotId *openapi_types.UUID `json:"spot_id,omitempty"`
}

// CreateSpotRequest defines model for CreateSpotRequest.
type CreateSpotRequest struct {
	AddressHint      *string `json:"address_hint,omitempty"`
	AutoCancelNoShow *bool   `json:"auto_cancel_no_show,omitempty"`
	Lat              float64 `json:"lat"`

	// LeavingNow «Me voy ya» — short-lived listing with ETA-only offers
	LeavingNow           *bool      `json:"leaving_now,omitempty"`
	Lon                  float64    `json:"lon"`
	Notes                *string    `json:"notes,omitempty"`
	PreferredDepartureAt *time.Time `json:"preferred_departure_at,omitempty"`
	PriceCents           int        `json:"price_cents"`
	SizeClass            string     `json:"size_class"`

	// VehicleId One of the caller's vehicles; required so claimers know which car to meet
	VehicleId openapi_types.UUID `json:"vehicle_id"`
}

// CreateVehicleRequest defines model for CreateVehicleRequest.
type CreateVehicleRequest struct {
	Color     string                        `json:"color"`
	MakeModel string                        `json:"make_model"`
	Plate     string                        `json:"plate"`
	SizeClass CreateVehicleRequestSizeClass `json:"size_class"`
	Year      int                           `json:"year"`
}

// CreateVehicleRequestSizeClass defines model for CreateVehicleRequest.SizeClass.
type CreateVehicleRequestSizeClass string

// ErrorBody defines model for ErrorBody.
type ErrorBody struct {
	Code      string             `json:"code"`
	Fields    *map[string]string `json:"fields,omitempty"`
	Message   string             `json:"message"`
	RequestId *string            `json:"request_id,omitempty"`
}

// ErrorEnvelope defines model for ErrorEnvelope.
type ErrorEnvelope struct {
	Error ErrorBody `json:"error"`
}

// ForgotPasswordRequest defines model for ForgotPasswordRequest.
type ForgotPasswordRequest struct {
	Email openapi_types.Email `json:"email"`
}

// GeoJSONPoint defines model for GeoJSONPoint.
type GeoJSONPoint struct {
	// Coordinates [longitude, latitude]
	Coordinates []float64        `json:"coordinates"`
	Type        GeoJSONPointType `json:"type"`
}

// GeoJSONPointType defines model for GeoJSONPoint.Type.
type GeoJSONPointType string

// GoogleLoginRequest defines model for GoogleLoginRequest.
type GoogleLoginRequest struct {
	IdToken string `json:"id_token"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status string `json:"status"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// OfferResponse defines model for OfferResponse.
type OfferResponse struct {
	AmountCents int                `json:"amount_cents"`
	CreatedAt   time.Time          `json:"created_at"`
	DriverId    openapi_types.UUID `json:"driver_id"`

	// DriverName Present when listing offers for the spot owner
	DriverName *string `json:"driver_name,omitempty"`

	// DriverRating Average stars when the driver has ratings; omitted if none
	DriverRating *float64 `json:"driver_rating,omitempty"`

	// DriverRatingCount Number of ratings received by the driver
	DriverRatingCount *int                `json:"driver_rating_count,omitempty"`
	ExchangeAt        time.Time           `json:"exchange_at"`
	ExpiresAt         time.Time           `json:"expires_at"`
	Id                openapi_types.UUID  `json:"id"`
	SpotId            openapi_types.UUID  `json:"spot_id"`
	Status            OfferResponseStatus `json:"status"`
	VehicleId         openapi_types.UUID  `json:"vehicle_id"`
}

// OfferResponseStatus defines model for OfferResponse.Status.
type OfferResponseStatus string

// PublicReview defines model for PublicReview.
type PublicReview struct {
	Comment   *string   `json:"comment,omitempty"`
	CreatedAt time.Time `json:"created_at"`
	RaterName string    `json:"rater_name"`
	Stars     int       `json:"stars"`
}

// PublicUserProfile defines model for PublicUserProfile.
type PublicUserProfile struct {
	DisplayName string             `json:"display_name"`
	Id          openapi_types.UUID `json:"id"`
	Rating      *float64           `json:"rating,omitempty"`
	RatingCount int                `json:"rating_count"`
	Reviews     []PublicReview     `json:"reviews"`
}

// RateReservationRequest defines model for RateReservationRequest.
type RateReservationRequest struct {
	Comment *string `json:"comment,omitempty"`
	Stars   int     `json:"stars"`
}

// RatingSummary defines model for RatingSummary.
type RatingSummary struct {
	Comment   *string   `json:"comment,omitempty"`
	CreatedAt time.Time `json:"created_at"`
	RaterName *string   `json:"rater_name,omitempty"`
	Stars     int       `json:"stars"`
}

// ReadyResponse defines model for ReadyResponse.
type ReadyResponse struct {
	Database string `json:"database"`
	Status   string `json:"status"`
}

// RefreshRequest defines model for RefreshRequest.
type RefreshRequest struct {
	RefreshToken string `json:"refresh_token"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	DisplayName string              `json:"display_name"`
	Email       openapi_types.Email `json:"email"`
	Password    string              `json:"password"`

	// Phone Optional E.164 phone; required before announcing a spot
	Phone *string `json:"phone,omitempty"`
}

// ReservationResponse defines model for ReservationResponse.
type ReservationResponse struct {
	// CanRate True when the caller may still submit a rating
	CanRate *bool `json:"can_rate,omitempty"`

	// CancelReason Why the reservation ended when status is cancelled/expired. Values include owner, driver, driver_late, driver_no_show, owner_no_show, safety_net, safety_net_owner_ready.
	CancelReason    *string            `json:"cancel_reason,omitempty"`
	CreatedAt       time.Time          `json:"created_at"`
	DriverEnRouteAt *time.Time         `json:"driver_en_route_at,omitempty"`
	DriverId        openapi_types.UUID `json:"driver_id"`
	DriverReadyAt   *time.Time         `json:"driver_ready_at,omitempty"`

	// DriverVehicle Driver's car from the accepted offer — visible to both parties
	DriverVehicle   *VehicleSummary     `json:"driver_vehicle,omitempty"`
	DriverVehicleId *openapi_types.UUID `json:"driver_vehicle_id,omitempty"`
	ExchangeAt      time.Time           `json:"exchange_at"`
	Id              openapi_types.UUID  `json:"id"`
	MyRating        *RatingSummary      `json:"my_rating,omitempty"`
	OfferId         *openapi_types.UUID `json:"offer_id,omitempty"`
	OwnerEnRouteAt  *time.Time          `json:"owner_en_route_at,omitempty"`
	OwnerId         openapi_types.UUID  `json:"owner_id"`
	OwnerReadyAt    *time.Time          `json:"owner_ready_at,omitempty"`

	// OwnerVehicle Car occupying the spot (owner) — visible to both parties
	OwnerVehicle *VehicleSummary    `json:"owner_vehicle,omitempty"`
	PeerRating   *RatingSummary     `json:"peer_rating,omitempty"`
	PriceCents   int                `json:"price_cents"`
	SpotId       openapi_types.UUID `json:"spot_id"`

	// SpotSummary Spot meeting point for list/detail UX (navigate + re-announce). Exact coords; both reservation parties already shared this place.
	SpotSummary *ReservationSpotSummary `json:"spot_summary,omitempty"`
	Status      string                  `json:"status"`
}

// ReservationSpotSummary defines model for ReservationSpotSummary.
type ReservationSpotSummary struct {
	AddressHint *string `json:"address_hint,omitempty"`
	Lat         float64 `json:"lat"`
	Lon         float64 `json:"lon"`

	// PriceCents Guide price from the original spot listing
	PriceCents int `json:"price_cents"`

	// VehicleId Owner vehicle that was listed on the spot
	VehicleId *openapi_types.UUID `json:"vehicle_id,omitempty"`
}

// ResetPasswordRequest defines model for ResetPasswordRequest.
type ResetPasswordRequest struct {
	Password string `json:"password"`
	Token    string `json:"token"`
}

// SessionResponse defines model for SessionResponse.
type SessionResponse struct {
	AccessToken string `json:"access_token"`

	// ExpiresIn Seconds remaining on the access token
	ExpiresIn    int          `json:"expires_in"`
	RefreshToken string       `json:"refresh_token"`
	TokenType    string       `json:"token_type"`
	User         UserResponse `json:"user"`
}

// SnapshotMessage Server to client WebSocket snapshot after a viewport
type SnapshotMessage struct {
	Features []SpotFeature       `json:"features"`
	Type     SnapshotMessageType `json:"type"`
}

// SnapshotMessageType defines model for SnapshotMessage.Type.
type SnapshotMessageType string

// SpotEventMessage Server to client incremental event
type SpotEventMessage struct {
	ExactLocation bool                 `json:"exact_location"`
	Id            openapi_types.UUID   `json:"id"`
	Lat           float64              `json:"lat"`
	Lon           float64              `json:"lon"`
	PriceCents    *int                 `json:"price_cents,omitempty"`
	Status        *string              `json:"status,omitempty"`
	Type          SpotEventMessageType `json:"type"`
}

// SpotEventMessageType defines model for SpotEventMessage.Type.
type SpotEventMessageType string

// SpotFeature defines model for SpotFeature.
type SpotFeature struct {
	Geometry   GeoJSONPoint    `json:"geometry"`
	Id         *string         `json:"id,omitempty"`
	Properties SpotProperties  `json:"properties"`
	Type       SpotFeatureType `json:"type"`
}

// SpotFeatureType defines model for SpotFeature.Type.
type SpotFeatureType string

// SpotFeatureCollection defines model for SpotFeatureCollection.
type SpotFeatureCollection struct {
	Features []SpotFeature             `json:"features"`
	Type     SpotFeatureCollectionType `json:"type"`
}

// SpotFeatureCollectionType defines model for SpotFeatureCollection.Type.
type SpotFeatureCollectionType string

// SpotProperties defines model for SpotProperties.
type SpotProperties struct {
	AddressHint      *string `json:"address_hint,omitempty"`
	AutoCancelNoShow bool    `json:"auto_cancel_no_show"`
	ExactLocation    bool    `json:"exact_location"`
	IsMine           bool    `json:"is_mine"`

	// LeavingNow Owner is leaving now («Me voy ya»)
	LeavingNow  *bool              `json:"leaving_now,omitempty"`
	ListedUntil time.Time          `json:"listed_until"`
	Notes       *string            `json:"notes,omitempty"`
	OwnerId     openapi_types.UUID `json:"owner_id"`
	OwnerName   string             `json:"owner_name"`

	// OwnerPhone Owner E.164 phone; only present when exact_location is true
	OwnerPhone           *string    `json:"owner_phone,omitempty"`
	OwnerRating          *float64   `json:"owner_rating,omitempty"`
	PreferredDepartureAt *time.Time `json:"preferred_departure_at,omitempty"`
	PriceCents           int        `json:"price_cents"`
	SizeClass            string     `json:"size_class"`
	Status               string     `json:"status"`

	// Vehicle Omitted until exact_location is true
	Vehicle *VehicleSummary `json:"vehicle,omitempty"`
}

// TicketResponse defines model for TicketResponse.
type TicketResponse struct {
	ExpiresIn int    `json:"expires_in"`
	Ticket    string `json:"ticket"`
}

// UpdateMeRequest defines model for UpdateMeRequest.
type UpdateMeRequest struct {
	DisplayName *string `json:"display_name,omitempty"`

	// Locale Preferred UI and push notification language
	Locale *UpdateMeRequestLocale `json:"locale,omitempty"`

	// Phone E.164 phone, or empty string to clear
	Phone *string `json:"phone,omitempty"`
}

// UpdateMeRequestLocale Preferred UI and push notification language
type UpdateMeRequestLocale string

// UpdateSpotRequest Partial edit of an available listing. Location, listing lifetime, and
// spot size_class are not editable.
type UpdateSpotRequest struct {
	AutoCancelNoShow     *bool               `json:"auto_cancel_no_show,omitempty"`
	Notes                *string             `json:"notes,omitempty"`
	PreferredDepartureAt *time.Time          `json:"preferred_departure_at,omitempty"`
	PriceCents           *int                `json:"price_cents,omitempty"`
	VehicleId            *openapi_types.UUID `json:"vehicle_id,omitempty"`
}

// UpdateVehicleRequest defines model for UpdateVehicleRequest.
type UpdateVehicleRequest struct {
	Color     string                        `json:"color"`
	MakeModel string                        `json:"make_model"`
	Plate     string                        `json:"plate"`
	SizeClass UpdateVehicleRequestSizeClass `json:"size_class"`
	Year      int                           `json:"year"`
}

// UpdateVehicleRequestSizeClass defines model for UpdateVehicleRequest.SizeClass.
type UpdateVehicleRequestSizeClass string

// UserResponse defines model for UserResponse.
type UserResponse struct {
	BalanceCents int64               `json:"balance_cents"`
	DisplayName  string              `json:"display_name"`
	Email        openapi_types.Email `json:"email"`

	// EmailVerified Whether the account may announce or reserve
	EmailVerified bool               `json:"email_verified"`
	Id            openapi_types.UUID `json:"id"`

	// Locale Preferred UI and push notification language
	Locale UserResponseLocale `json:"locale"`

	// Phone E.164 phone number of this account; empty when unset
	Phone       string   `json:"phone"`
	Rating      *float64 `json:"rating,omitempty"`
	RatingCount int      `json:"rating_count"`
}

// UserResponseLocale Preferred UI and push notification language
type UserResponseLocale string

// VehicleResponse defines model for VehicleResponse.
type VehicleResponse struct {
	Color     string                   `json:"color"`
	CreatedAt time.Time                `json:"created_at"`
	HasPhoto  bool                     `json:"has_photo"`
	Id        openapi_types.UUID       `json:"id"`
	MakeModel string                   `json:"make_model"`
	Plate     string                   `json:"plate"`
	SizeClass VehicleResponseSizeClass `json:"size_class"`
	UpdatedAt time.Time                `json:"updated_at"`
	Year      int                      `json:"year"`
}

// VehicleResponseSizeClass defines model for VehicleResponse.SizeClass.
type VehicleResponseSizeClass string

// VehicleSummary Claimer-visible car identity embedded on spot features
type VehicleSummary struct {
	Color     string                  `json:"color"`
	HasPhoto  bool                    `json:"has_photo"`
	Id        openapi_types.UUID      `json:"id"`
	MakeModel string                  `json:"make_model"`
	Plate     string                  `json:"plate"`
	SizeClass VehicleSummarySizeClass `json:"size_class"`
	Year      int                     `json:"year"`
}

// VehicleSummarySizeClass defines model for VehicleSummary.SizeClass.
type VehicleSummarySizeClass string

// VersionResponse defines model for VersionResponse.
type VersionResponse struct {
	BuildTime string `json:"build_time"`
	GoVersion string `json:"go_version"`
	Revision  string `json:"revision"`
	Version   string `json:"version"`
}

// ViewportMessage Client to server WebSocket message
type ViewportMessage struct {
	// Bbox [west, south, east, north]
	Bbox []float64  `json:"bbox"`
	From *time.Time `json:"from,omitempty"`

	// IncludeFlexible When true, include flexible (non-leaving-now) spots. Defaults to true when omitted.
	IncludeFlexible *bool `json:"include_flexible,omitempty"`

	// IncludeLeavingNow When true, include «Me voy ya» listings. Defaults to true when omitted.
	IncludeLeavingNow *bool `json:"include_leaving_now,omitempty"`

	// LeavingNowOnly When true, return only leaving_now listings.
	LeavingNowOnly *bool               `json:"leaving_now_only,omitempty"`
	To             *time.Time          `json:"to,omitempty"`
	Type           ViewportMessageType `json:"type"`
	Zoom           *int                `json:"zoom,omitempty"`
}

// ViewportMessageType defines model for ViewportMessage.Type.
type ViewportMessageType string

// BBox defines model for BBox.
type BBox = string

// From defines model for From.
type From = time.Time

// IncludeFlexible defines model for IncludeFlexible.
type IncludeFlexible = bool

// IncludeLeavingNow defines model for IncludeLeavingNow.
type IncludeLeavingNow = bool

// LeavingNowOnly defines model for LeavingNowOnly.
type LeavingNowOnly = bool

// OfferID defines model for OfferID.
type OfferID = openapi_types.UUID

// ReservationID defines model for ReservationID.
type ReservationID = openapi_types.UUID

// SpotID defines model for SpotID.
type SpotID = openapi_types.UUID

// To defines model for To.
type To = time.Time

// VehicleID defines model for VehicleID.
type VehicleID = openapi_types.UUID

// Zoom defines model for Zoom.
type Zoom = int

// Error defines model for Error.
type Error = ErrorEnvelope

// OpenEmailVerificationParams defines parameters for OpenEmailVerification.
type OpenEmailVerificationParams struct {
	Token string `form:"token" json:"token"`
}

// PutPushTokenJSONBody defines parameters for PutPushToken.
type PutPushTokenJSONBody struct {
	Platform PutPushTokenJSONBodyPlatform `json:"platform"`

	// Token ExponentPushToken[...]
	Token string `json:"token"`
}

// PutPushTokenJSONBodyPlatform defines parameters for PutPushToken.
type PutPushTokenJSONBodyPlatform string

// ListSpotsParams defines parameters for ListSpots.
type ListSpotsParams struct {
	// Bbox minLon,minLat,maxLon,maxLat
	Bbox BBox  `form:"bbox" json:"bbox"`
	Zoom *Zoom `form:"zoom,omitempty" json:"zoom,omitempty"`

	// From Inclusive start of the time window (RFC3339)
	From *From `form:"from,omitempty" json:"from,omitempty"`

	// To Exclusive end of the time window (RFC3339)
	To *To `form:"to,omitempty" json:"to,omitempty"`

	// IncludeFlexible When true, include flexible (non-preferred, non-leaving-now) spots
	IncludeFlexible *IncludeFlexible `form:"include_flexible,omitempty" json:"include_flexible,omitempty"`

	// IncludeLeavingNow When true, include «Me voy ya» listings
	IncludeLeavingNow *IncludeLeavingNow `form:"include_leaving_now,omitempty" json:"include_leaving_now,omitempty"`

	// LeavingNowOnly When true, return only leaving_now listings
	LeavingNowOnly *LeavingNowOnly `form:"leaving_now_only,omitempty" json:"leaving_now_only,omitempty"`
}

// GetUserProfileParams defines parameters for GetUserProfile.
type GetUserProfileParams struct {
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// OpenWebSocketParams defines parameters for OpenWebSocket.
type OpenWebSocketParams struct {
	// Ticket Ticket from POST /v1/ws/tickets; not an access token
	Ticket string `form:"ticket" json:"ticket"`
}

// LoginWithGoogleJSONRequestBody defines body for LoginWithGoogle for application/json ContentType.
type LoginWithGoogleJSONRequestBody = GoogleLoginRequest

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// LogoutJSONRequestBody defines body for Logout for application/json ContentType.
type LogoutJSONRequestBody = RefreshRequest

// ForgotPasswordJSONRequestBody defines body for ForgotPassword for application/json ContentType.
type ForgotPasswordJSONRequestBody = ForgotPasswordRequest

// ResetPasswordJSONRequestBody defines body for ResetPassword for application/json ContentType.
type ResetPasswordJSONRequestBody = ResetPasswordRequest

// RefreshJSONRequestBody defines body for Refresh for application/json ContentType.
type RefreshJSONRequestBody = RefreshRequest

// RegisterJSONRequestBody defines body for Register for application/json ContentType.
type RegisterJSONRequestBody = RegisterRequest

// ConfirmEmailJSONRequestBody defines body for ConfirmEmail for application/json ContentType.
type ConfirmEmailJSONRequestBody = ConfirmEmailRequest

// UpdateMeJSONRequestBody defines body for UpdateMe for application/json ContentType.
type UpdateMeJSONRequestBody = UpdateMeRequest

// ChangePasswordJSONRequestBody defines body for ChangePassword for application/json ContentType.
type ChangePasswordJSONRequestBody = ChangePasswordRequest

// PutPushTokenJSONRequestBody defines body for PutPushToken for application/json ContentType.
type PutPushTokenJSONRequestBody PutPushTokenJSONBody

// CreateReportJSONRequestBody defines body for CreateReport for application/json ContentType.
type CreateReportJSONRequestBody = CreateReportRequest

// RateReservationJSONRequestBody defines body for RateReservation for application/json ContentType.
type RateReservationJSONRequestBody = RateReservationRequest

// CreateSpotJSONRequestBody defines body for CreateSpot for application/json ContentType.
type CreateSpotJSONRequestBody = CreateSpotRequest

// UpdateSpotJSONRequestBody defines body for UpdateSpot for application/json ContentType.
type UpdateSpotJSONRequestBody = UpdateSpotRequest

// CreateOfferJSONRequestBody defines body for CreateOffer for application/json ContentType.
type CreateOfferJSONRequestBody = CreateOfferRequest

// CreateVehicleJSONRequestBody defines body for CreateVehicle for application/json ContentType.
type CreateVehicleJSONRequestBody = CreateVehicleRequest

// UpdateVehicleJSONRequestBody defines body for UpdateVehicle for application/json ContentType.
type UpdateVehicleJSONRequestBody = UpdateVehicleRequest
