#!/usr/bin/env bash
# Activate apps/mobile API target for Expo (writes .env.development.local).
# Usage:
#   tools/mobile-use-env.sh emulator
#   tools/mobile-use-env.sh device [LAN_IP]
#   tools/mobile-use-env.sh device-init [LAN_IP]
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
APP="$ROOT/apps/mobile"
TARGET="${1:-}"
IP_ARG="${2:-}"

die() {
  echo "error: $*" >&2
  exit 1
}

detect_lan_ip() {
  local ip=""
  if command -v powershell.exe >/dev/null 2>&1; then
    ip="$(
      powershell.exe -NoProfile -Command \
        "(Get-NetIPAddress -AddressFamily IPv4 |
          Where-Object {
            \$_.PrefixOrigin -ne 'WellKnown' -and
            \$_.IPAddress -notlike '169.*' -and
            \$_.InterfaceAlias -match 'Wi-?Fi|WLAN|Wireless'
          } |
          Sort-Object InterfaceMetric |
          Select-Object -First 1 -ExpandProperty IPAddress)" \
        2>/dev/null | tr -d '\r' | tr -d ' '
    )"
  fi
  if [ -z "$ip" ] && command -v ip >/dev/null 2>&1; then
    ip="$(ip route get 1.1.1.1 2>/dev/null | awk '{for (i = 1; i <= NF; i++) if ($i == "src") { print $(i + 1); exit }}')"
  fi
  if [ -z "$ip" ]; then
    ip="$(hostname -I 2>/dev/null | awk '{print $1}')"
  fi
  printf '%s' "$ip"
}

write_device_env() {
  local ip="$1"
  [ -n "$ip" ] || die "no LAN IP — pass one: task mobile:env:device -- 192.168.1.38"
  cat >"$APP/.env.device" <<EOF
# Physical Android device on the same Wi-Fi as this PC (gitignored).
# Regenerated by: task mobile:env:device   or   task mobile:env:device -- <ip>
EXPO_PUBLIC_API_URL=http://${ip}:8080
EXPO_PUBLIC_WS_URL=ws://${ip}:8080/v1/ws
EOF
  echo "Wrote $APP/.env.device → http://${ip}:8080"
}

activate() {
  local src="$1"
  local label="$2"
  [ -f "$src" ] || die "missing $src"
  cp "$src" "$APP/.env.development.local"
  echo "Mobile env → ${label}"
  grep -E '^EXPO_PUBLIC_(API|WS)_URL=' "$APP/.env.development.local" || true
}

case "$TARGET" in
  emulator)
    activate "$APP/.env.emulator" "emulator (10.0.2.2)"
    ;;
  device-init)
    write_device_env "${IP_ARG:-$(detect_lan_ip)}"
    ;;
  device)
    if [ -n "$IP_ARG" ] || [ ! -f "$APP/.env.device" ]; then
      write_device_env "${IP_ARG:-$(detect_lan_ip)}"
    fi
    activate "$APP/.env.device" "physical device"
    ;;
  *)
    die "usage: $0 emulator|device|device-init [LAN_IP]"
    ;;
esac
